% function to determine generic values for HW SW accelerator

function [] = determine_generics(num_bands,pixbw,brambw,outbw)

 clc;
 add_frac = ceil(log2(num_bands));

 ST2IN_DATA_WIDTH = outbw;           
 ST3IN_DATA_WIDTH = outbw; 
 
 BRAM_ADDR_WIDTH = ceil(log2(num_bands));
 BRAM_ROW_WIDTH = num_bands*brambw;
 
 %sliders stage 2 input
 ST2IN_DATA_SLIDER = pixbw + brambw + add_frac - 2;
 
 %ASMF specific sliders
 %by default 
 %ST2_ASMF2_DATA_SLIDER = (pixbw + ST2IN_DATA_WIDTH + add_frac)*2 - 2;
 %but
 ST2_ASMF2_DATA_SLIDER = 72;
 
 %by default 
 %ST2_ASMF2SR_DATA_SLIDER = ST2IN_DATA_WIDTH*2 - 2;
 %but
 ST2_ASMF2SR_DATA_SLIDER = 46;
 
 %sliders stage 3 input
 ST3IN_DATA1_SLIDER =  pixbw + ST2IN_DATA_WIDTH + add_frac - 2;
 ST3IN_DATA2_SLIDER = ST2IN_DATA_WIDTH*2 -2;
 
  
 %sliders stage 3 output-divider input
 OUT_DATA1_SLIDER = ST3IN_DATA_WIDTH + brambw -2;
 OUT_DATA2_SLIDER = ST3IN_DATA_WIDTH -1;
 
 
 print_string =['PIXEL_DATA_WIDTH   : positive := %d; \n',...
               'BRAM_DATA_WIDTH    : positive := %d; \n',...
                'ST2IN_DATA_WIDTH   : positive := %d; \n',...
                'ST3IN_DATA_WIDTH   : positive := %d; \n',...
                'ST2IN_DATA_SLIDER  : positive := %d; \n',...
                'ST2_ASMF2_DATA_SLIDER 	: positive := %d; \n',...
                'ST2_ASMF2SR_DATA_SLIDER	: positive := %d; \n',...
                'ST3IN_DATA1_SLIDER : positive := %d; \n',...
                'ST3IN_DATA2_SLIDER : positive := %d; \n',...
                'NUM_BANDS          : positive := %d; \n',...
                'PACKET_SIZE        : positive := %d; \n',...
                'OUT_DATA_WIDTH     : positive := %d; \n',...
                'OUT_DATA1_SLIDER   : positive := %d; \n',...
                'OUT_DATA2_SLIDER   : positive := %d; \n',...
                'BRAM_ADDR_WIDTH    : integer  := %d;  \n',...
                'BRAM_ROW_WIDTH     : positive := %d \n'];            
            
fprintf(print_string,pixbw,brambw,ST2IN_DATA_WIDTH,ST3IN_DATA_WIDTH,...
        ST2IN_DATA_SLIDER,ST2_ASMF2_DATA_SLIDER,ST2_ASMF2SR_DATA_SLIDER,...
        ST3IN_DATA1_SLIDER,ST3IN_DATA2_SLIDER,...
        num_bands,num_bands,outbw,...
        OUT_DATA1_SLIDER,OUT_DATA2_SLIDER,BRAM_ADDR_WIDTH,BRAM_ROW_WIDTH);


end